services:
  - type: web
    name: speechdaddy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHONPATH
        value: .
    healthCheckPath: /health 